---
title: Star - 宇星
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  gallery:
    title: gallery
    output: true
brief-intro: O ever youthful, O ever weeping.
baseurl: ''
url: http://liaoyuxing.space
reading_time: true
words_per_minute: 200
logo: "/favicon.png"
permalink: "/:year/:month/:day/:title/"
facebook_username: liaoyuxing1001
github_username: vvstars
email: u_stars@foxmail.com
weibo_username: liaoyuxing1001
zhihu_username: 
linkedIn_username: 
dribbble_username: 
description_footer: 本站记录我青春的沿途风景！
description: 廖宇星的个人博客，关注web前端开发，麦肯锡公司以及摄影技术，尤其喜欢森山大道。 博客主要记录个人生活读书笔记，关于web前端开发的一些知识，整个麦肯锡的朝圣之路以及个人摄影作品
  画廊，有必要的话将开栏目写一些摄影文章。
duoshuo_shortname: liaoyuxing
disqus_shortname: 
baidu_tongji_id: 58bd04cf6c6dbb33303a5fe9862782b8
google_analytics_id: UA-86467042-1
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
category_dir: category/
tag_dir: tag/
excerpt_separator: |2+




gems:
- jekyll-paginate
paginate: 6
