# Site
title:              Star | 宇星的博客
bio:                'Star, a dreamer in the universe.'
description:        "Star is a blog, belong to liaoyuxing."
keyword: "廖宇星,宇星,廖宇星的博客,博客,jekyll,Yux,个人网站,麻雪妍的男朋友,麻雪妍,麻雪妍的男朋友的博客"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.jpg'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             cn_China
url:                http://liaoyuxing.space/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed
email: u_stars@foxmail.com
# Comments
#disqus_shortname:   liaoyuxing
duoshuo_username:   liaoyuxing
duoshuo_share:      false

# Analytics settings
# Baidu Analytics
ba_track_id: 0614ad53bafda60cf7bba42be50502af
# Google Analytics
ga_track_id: 'UA-84827030-1'            # Format: UA-xxxxxx-xx
#ga_domain: vvstars.gitHub.io

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            LuiseLiao
facebook:           liaoyuxing1001
github:             vvstars
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
weibo:             liaoyuxing1001
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
